server:
  port: 8001

spring:
  application:
    name: request-app
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: "guest"
    password: "guest"
  redis:
    port: 6379
    host: 127.0.0.1

app:
  mq:
    in:
      exchangeName: "res-msg-exchange"
      queueName: "response"
    out:
      exchangeName: "req-msg-exchange"
      queueName: "request"
  cache:
    delayInMs: 100
    expirationTimeInSec: 2
